import os
import sys
import argparse
import csv
import json
import random
import pandas as pd
import numpy as np
import cv2

# Set path to allow imports from src/
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from src.utils.seed import set_seed
from src.utils.config import CONFIG
from src.vision.aruco_detector import detect_aruco_markers

def main():
    parser = argparse.ArgumentParser(description="Unity Dataset Post-Processor and Compatibility Layer")
    parser.add_argument("--dataset_dir", type=str, default="final_project/unity_dataset", help="Unity dataset directory")
    parser.add_argument("--seed", type=int, default=CONFIG["dataset"]["seed"], help="Random seed for splitting")
    args = parser.parse_args()

    set_seed(args.seed)

    csv_path = os.path.join(args.dataset_dir, "labels.csv")
    raw_dir = os.path.join(args.dataset_dir, "raw")
    splits_dir = os.path.join(args.dataset_dir, "splits")
    metrics_dir = "final_project/results/metrics"

    if not os.path.exists(csv_path):
        print(f"Error: {csv_path} not found. Make sure Unity generated the dataset first!")
        sys.exit(1)

    os.makedirs(splits_dir, exist_ok=True)
    os.makedirs(metrics_dir, exist_ok=True)

    print(f"Post-processing Unity dataset at {args.dataset_dir}...")

    # Load labels generated by Unity
    df = pd.read_csv(csv_path)
    
    # Check if we already postprocessed it
    required_cols = ["marker_center_x", "marker_center_y", "marker_area", "m10_visible"]
    is_already_processed = all(col in df.columns for col in required_cols)
    
    if is_already_processed:
        print("Dataset seems to have been already post-processed. Re-running splits only.")
    else:
        # We need to process each image to add ArUco features
        print(f"Detecting ArUco markers in {len(df)} images...")
        
        # New columns lists
        p_cxs, p_cys, p_areas = [], [], []
        marker_features = {
            10: {"visible": [], "cx": [], "cy": [], "area": []},
            11: {"visible": [], "cx": [], "cy": [], "area": []},
            12: {"visible": [], "cx": [], "cy": [], "area": []},
            13: {"visible": [], "cx": [], "cy": [], "area": []}
        }
        
        total_boxes = 0
        average_occupancy_sum = 0.0
        marker_visible_count = 0
        marker_visibility_counts = {10: 0, 11: 0, 12: 0, 13: 0}

        for idx, row in df.iterrows():
            img_rel_path = row["image_path"]
            img_full_path = os.path.join(args.dataset_dir, img_rel_path)
            
            img = cv2.imread(img_full_path)
            visible = detect_aruco_markers(img)

            # Largest marker features
            p_cx, p_cy, p_area = 0.0, 0.0, 0.0
            if visible:
                marker_visible_count += 1
                visible.sort(key=lambda x: x["area"], reverse=True)
                largest = visible[0]
                p_cx = largest["cx"]
                p_cy = largest["cy"]
                p_area = largest["area"]

            p_cxs.append(p_cx)
            p_cys.append(p_cy)
            p_areas.append(p_area)

            # Fixed-length markers (10, 11, 12, 13)
            current_m_data = {
                10: {"visible": 0.0, "cx": 0.0, "cy": 0.0, "area": 0.0},
                11: {"visible": 0.0, "cx": 0.0, "cy": 0.0, "area": 0.0},
                12: {"visible": 0.0, "cx": 0.0, "cy": 0.0, "area": 0.0},
                13: {"visible": 0.0, "cx": 0.0, "cy": 0.0, "area": 0.0}
            }

            for m in visible:
                m_id = m["id"]
                if m_id in current_m_data:
                    current_m_data[m_id] = {
                        "visible": 1.0,
                        "cx": m["cx"],
                        "cy": m["cy"],
                        "area": m["area"]
                    }
                    marker_visibility_counts[m_id] += 1

            for m_id in [10, 11, 12, 13]:
                marker_features[m_id]["visible"].append(current_m_data[m_id]["visible"])
                marker_features[m_id]["cx"].append(current_m_data[m_id]["cx"])
                marker_features[m_id]["cy"].append(current_m_data[m_id]["cy"])
                marker_features[m_id]["area"].append(current_m_data[m_id]["area"])

            if (idx + 1) % 200 == 0:
                print(f"  Processed {idx + 1}/{len(df)} images...")

        # Add columns to dataframe
        df["marker_center_x"] = p_cxs
        df["marker_center_y"] = p_cys
        df["marker_area"] = p_areas

        for m_id in [10, 11, 12, 13]:
            df[f"m{m_id}_visible"] = marker_features[m_id]["visible"]
            df[f"m{m_id}_cx"] = marker_features[m_id]["cx"]
            df[f"m{m_id}_cy"] = marker_features[m_id]["cy"]
            df[f"m{m_id}_area"] = marker_features[m_id]["area"]

        # Overwrite CSV with full compatible data
        df.to_csv(csv_path, index=False)
        print(f"Updated CSV with OpenCV marker features: {csv_path}")

    # Perform splits
    num_samples = len(df)
    indices = list(range(num_samples))
    random.shuffle(indices)

    train_pct = CONFIG["dataset"]["split_train"]
    val_pct = CONFIG["dataset"]["split_val"]

    train_idx_end = int(num_samples * train_pct)
    val_idx_end = train_idx_end + int(num_samples * val_pct)

    train_df = df.iloc[indices[:train_idx_end]]
    val_df = df.iloc[indices[train_idx_end:val_idx_end]]
    test_df = df.iloc[indices[val_idx_end:]]

    train_df.to_csv(os.path.join(splits_dir, "train.csv"), index=False)
    val_df.to_csv(os.path.join(splits_dir, "val.csv"), index=False)
    test_df.to_csv(os.path.join(splits_dir, "test.csv"), index=False)

    print(f"Saved dataset splits to {splits_dir}")

    # Generate summary stats
    total_boxes = df["box_count"].sum()
    avg_occupancy = df["shelf_occupancy"].mean()
    m_vis_count = (df["marker_area"] > 0).sum()
    
    summary = {
        "total_samples": num_samples,
        "train_samples": len(train_df),
        "val_samples": len(val_df),
        "test_samples": len(test_df),
        "total_boxes": int(total_boxes),
        "average_occupancy": float(avg_occupancy),
        "marker_visibility_rate": float(m_vis_count / num_samples),
        "marker_counts": {
            "10": int(df["m10_visible"].sum()) if "m10_visible" in df else 0,
            "11": int(df["m11_visible"].sum()) if "m11_visible" in df else 0,
            "12": int(df["m12_visible"].sum()) if "m12_visible" in df else 0,
            "13": int(df["m13_visible"].sum()) if "m13_visible" in df else 0
        }
    }

    summary_path = os.path.join(metrics_dir, "unity_dataset_summary.json")
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=4)

    print(f"Summary statistics saved to: {summary_path}")
    print("Post-processing completed successfully!")

if __name__ == "__main__":
    main()
